language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

branches:
  only:
    - short_tags_travis
    - master

services:
  - mysql

before_install:
  - sudo add-apt-repository -y ppa:mc3man/trusty-media
  - sudo apt-get update -qq
  - sudo apt-get install -qq graphicsmagick imagemagick php5-gd ffmpeg git-core

before_script:
  - mysql -e 'create database gallery3; create database gallery3_test;'
  - php ./installer/index.php

script:
  - 'php index.php test'
